NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca-moi-ps-8054-ca-moi.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca-moi-ps-8054-ca-moi.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca-moi-ps-8054-ca-moi.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca-moi-ps-8054-ca-moi.pem
    OrganizationalUnitIdentifier: orderer
